from frameSetStudent import *
from leskUtils import * 

import os

# cd /Users/aleclock/Desktop/uni/TLN/radicioni/progettoTLN_Radicioni/esercizio3_FN

"""
Save the annotation in form:    type, frame_name, element, synset
Input:
    path: path of file
    synset: synset mapped to frame element
"""
def annotateMapping (path, synset):
    if synset != None:
        file = open(path, 'a')
        #file.write(el + ", " + fn.frame(frame).name + ", " + str(synset) +"\n")
        for i in synset:
            file.write(i[0] + ", " + i[1] + ", " + i[2] + ", " + str(i[3]) + "\n")
        file.close()

"""
Delete file in path
Input: 
    path: path of file
"""
def clear_file(path):
    os.remove(path)

"""
Read the file in path and extract a list
Input:
    path: path of file
Output:
    ann: list of manual annotation (mapped synset)
"""
def extractSynsetFromAnnotation(path):
    ann = []
    file = open(path, encoding="utf8")
    for line in file.readlines():
        if line != "":
            line_splitted = line.split(",")
            ann.append([item.strip() for item in line_splitted])
    return ann

"""
Compare the manual annotation (ann_in) with the annotation generated by program (ann_out)
Input:
    ann_in: manual annotation
    ann_out: automatic annotation (made by program)
Output:
    score
"""
def compareAnnotation(ann_in, ann_out):
    correct = 0
    for i in range (0, len(ann_in)):
        if ann_in[i] == ann_out[i]:
            correct += 1
    return (correct/len(ann_in))


def main ():

    clear_file ("./ann_output.txt")

    # ---------------------------------------------
    # ----      0. INDIVIDUAZIONE DI UN SET DI FRAME
    # Come prima operazione ciascuno deve individuare un insieme di frame (nel seguito riferito come FrameSet) su cui deve lavorare.
    # La funzione restituisce, dato un cognome in input, l'elenco di frame da elaborare.
    # ---------------------------------------------

    #frameSet = getFrameSetForStudent('Clocchiatti')
    frameSet = [31, 120, 1030, 1771, 2303] # id
    
    # ---------------------------------------------
    # ----      1. ASSEGNAZIONE DI UN WN SYNSET AD UN ELEMENTO FRAMENET
    # Per ogni frame nel FrameSet è necessario assegnare un WN synset ai seguenti elementi: Frame name, Frame Elements (FEs) del frame e Lexical Units (LUs)
    # ---------------------------------------------

    #for f in frameSet[:1]:
    for f in frameSet[:]:
        f_name = getFrameName(f)
        f_FE = getFrameElements(f)
        f_LU = getFrameLU(f)

        print ("Analayzing frame: " + getFrame(f).name)
        
        ctx_frame = getFrameContext(f, f_FE)
        
        syn_fname = getWNSynset(f, f_name, ctx_frame, 0)
        syn_fe = getWNSynset(f, f_FE, ctx_frame, 1)
        syb_lu = getWNSynset(f, f_LU, ctx_frame, 2) 

        annotateMapping ("./ann_output.txt", syn_fname)
        annotateMapping ("./ann_output.txt", syn_fe)
        annotateMapping ("./ann_output.txt", syb_lu)

        print ("--------------------------------------------------------------------------------")

    # ---------------------------------------------
    # ----      2. VALUTAZIONE DELL'OUTPUT DEL SISTEMA
    # Il programma implementato dovrà quindi fornire anche la funzionalità di valutazione, che confronterà i synset restituiti in output dal sistema 
    # con quelli annotati a mano dallo studente; su questa base deve essere calcolata l'accuratezza del sistema, 
    # semplicemente come rapporto dei corretti sul totale.
    # ---------------------------------------------
    
    ann_in = extractSynsetFromAnnotation("./ann_input.txt")
    ann_out = extractSynsetFromAnnotation("./ann_output.txt")
    score = compareAnnotation(ann_in,ann_out)

    print ("Output evaluation: " + str(score))

main()